lifinance/types

package.json
src/api.ts
src/exchanges.ts
src/step.ts

Updates the step types and at the same time tests how to automatically build the types if needed

LF-91: new step types

---

src/base.ts

Add block number of current block during balance retrieval to TokenAmounts

feat(TokenAmount): add blockNumbers to TokenAmounts

---

CHANGELOG.md
README.md
package.json
yarn.lock

Setup conventional-changelog for releases and update documentation

docs: setup conventional-changelog

---

src/step.ts

This field allows to pass a HTML formatted error message with additional information for the user

feat(Process): add htmlErrorMessage field

---

src/assets/tokens/stellaswap.json
src/coins.ts
src/exchanges.ts

- added StellaSwap token list JSON according to their token list
( https://docs.stellaswap.com/resources/how-to-guides/wallet-and-network/token-address-list-for-manual-import )
- enabled StellaSwap on `exchanges.ts`

LF-717 :  add more DEX on moonbeam chain

---

src/step.ts
tsconfig.json

This PR adds `toolDetails` to the StepBase object.

feat: supporting types for LF-770

---

README.md
git.README.md
npm.README.md
src/api.ts
src/bridges.ts
src/exchanges.ts

These are supporting types for the tools and types refactoring proposal (LF-508)

fix(deprecation): marked methods and constants as deprecated (LF-766)

---

src/coins.ts

they were removed accidentally

fix(coin): add coin keys again

---

src/coins.ts

feat: add solana tokens to coins

---

src/api.ts

This reverts commit f2be8362c4cad7227dba9ff4d4d9d885b9de4bc5.

Revert "feat: make properties of Interface GetStatusRequest optional"

---

src/api.ts

Supporting types for trusted gas feature

feat: trusted gas parameter for routes and quote request

---

src/api.ts

fix: rename flag for max price impact

---

src/api.ts

This reverts commit 0eb8f1bca49f960f8f79d37fac4c94a5c14505a4.

Revert "fix: make insurance on route optional (#143)"

---

src/coins.ts

Add Linea (formerly CZKT) test token
https://explorer.goerli.linea.build/address/0xB706319D37b945727E71ae0d4353699d19112576

fix: add Linea Test token

---

src/base.ts
src/coins.ts

https://lifi.atlassian.net/browse/LF-3261

fix: differentiate between USDC and USDC.e

---

src/coins.ts
test/types.unit.test.ts

The fn was not taking coin names, logoURIs and keys into account.

fix: findTokenByChainIdAndAddress was broken

---

src/base.ts
src/chains/supported.chains.ts
src/multicall.ts

https://lifi.atlassian.net/browse/LF-3754

feat: add LNA and update multicall addresses

---

src/chains/supported.chains.ts
src/coins.ts

https://lifi.atlassian.net/browse/LF-3765

feat: add Linea

---

src/coins.ts

fix: do not lowercase token addresses

---

src/coins.ts

https://lifi.atlassian.net/browse/LF-5317

chore: new usdc on pol

---

src/api.ts

This reverts commit 25158daef42e44faf336be4d6fa97ed045df8050.

Revert "chore: add integrator on FullStatusData"

---

src/api.ts

BREAKING CHANGE: extend FullStatusData to include metadata

feat!: add metadata to FullStatusData

---

src/api.ts

https://lifi.atlassian.net/browse/LF-6172

feat: add value to ExtendedTransactionInfo

---

src/api.ts

https://lifi.atlassian.net/browse/LF-6535

feat: add failedStatusData type

---

src/api.ts

https://lifi.atlassian.net/browse/LF-4536

feat: add integrator request types

---

src/chains/base.ts

feat!: remove GOR and MUM chains support

---

src/api.ts

https://lifi.atlassian.net/browse/LF-7495

feat!: remove NOT_PROCESSABLE_REFUND_NEEDED substatus

---

src/errors.ts

Adding RpcFailure + MalformedSchema error codes to distinguish backend failures.

feat: add RpcFailure + MalformedSchema error codes

---

README.md
src/errors.ts

Added missing release documentation

docs: update release readme

---

.github/workflows/publish.yaml

chore: update publish action

---

src/api.ts

Related to https://lifi.atlassian.net/browse/LF-8403
- Update `TransferSummariesResponse` API response interface to a paginated reponse
- Minor comments to pagination interfaces

feat: paginated TransferSummariesResponse

---

src/api.ts

**https://lifi.atlassian.net/browse/LF-8826**

docs: deprecate RECOMMENDED and SAFEST

---

src/api.ts

Ref: 9276
Add new `minPriceUSD` parameter to `TokensRequest`

feat: add minPriceUSD parameter to TokensRequest

---

src/api.ts

Adds request interface for quote toAmount
https://lifi.atlassian.net/browse/LF-6611

feat: add quote toAmount req interface

---

src/tokens/base.ts

Jumper team wanna the icon of alxusdc, I wanna add alxUSDC here first, then update the data-types

feat: add alxUSDC token

---

src/api.ts

Needed for adding stepTransaction data to /status endpoint on BE (for exposing fee costs)
https://github.com/lifinance/lifi-backend/pull/5694

chore: added stepTransaction field to status data

---

src/step.ts

Revert "feat: remove sdk specific types"

---

CHANGELOG.md
package.json
src/chains/base.ts

Also fixed the changelog, i messed that up in the last PR

feat(chain): add Corn

---

.github/workflows/semantic-pr.yml
.husky/commit-msg

https://lifi.atlassian.net/browse/LF-12564

feat: introduce semantic pr

---

src/chains/base.ts
src/tokens/base.ts

feat: add HyperEVM
