src/step.ts

This status is needed to indicate that the SDK caller needs to perform a chain switch to proceed with the execution

feat(Status): add CHAIN_SWITCH_REQUIRED status

---

src/api.ts

Until we decided what to do with the /connections endpoint we remove it from the types not not block deployments

fix: remove connections endpoint

---

src/step.ts

It can be that the received token changes due to failures in the destination swap. To be able to show the received token we need to store it in the execution object.

feat: add toToken to Execution

---

src/coins.ts

The CELO token does have the address zero:
https://explorer.celo.org/address/0x0000000000000000000000000000000000000000
https://explorer.celo.org/token/0x471EcE3750Da237f93B8E339c536989b8978a438

fix: update celo token address

---

src/coins.ts

It has 18 decimals, not 8: https://optimistic.etherscan.io/token/0x4200000000000000000000000000000000000006

fix: fix decimals of WETH on Optimism

---

src/coins.ts

We use ARB testnet for our arbitrum bridge tests, we need to find the wrapped gas token for it.

feat: add wrapped gas for ARBT

---

src/api.ts

Even though the suggested types were 
```typescript
type ToolsResponse = {
exchanges: Exchange[]
bridges: Bridge[]
}
type Exchange = {
tool: ExchangeTools
chains: number[]
}
```
I have renamed them to 
```typescript
export type ExternalExchange = {
tool: ExchangeTools
chains: number[]
}
export type ExternalBridge = {
tool: BridgeTool
chains: number[]
}
```
to avoid collision with the already declared types `Exchange` and `Bridge`.

feat: added required types for LF-672

---

src/multicall.ts

The previous contract (https://optimistic.etherscan.io/address/0x142e2feac30d7fc3b61f9ee85fccad8e560154cc#code) was multicallv1 instead of v2 -- v1 does not have the method we use `tryAggregate`.

fix: updated multicall contract to multicallv2

---

src/coins.ts

I fetched those names by calling debank with this script in the backend:
```typescript
const results = []
const failures = []
for (const coin of defaultCoins) {
for (const chain in coin.chains) {
const chainItem = getChainById(parseInt(chain))
if (!chainItem.mainnet) {
continue
}
const token = coin.chains[chain]
try {
const updatedToken = await tokenService.getTokenFromDebankApi(
token.chainId,
deepClone(token)
)
results.push([token, updatedToken])
} catch {
failures.push(token)
}
}
}
// wrapped native tokens
for (const chain in wrappedTokens) {
const chainItem = getChainById(parseInt(chain))
if (!chainItem.mainnet) {
continue
}
const token = wrappedTokens[chain]
try {
const updatedToken = await tokenService.getTokenFromDebankApi(
token.chainId,
deepClone(token)
)
results.push([token, …
```

fix(coins): update names and symbols or tokens

---

src/bridges.ts
src/chains/supported.chains.ts
src/exchanges.ts

We agreed to rename `Arbitrum One` and `Arbitrum One Bridge` to `Arbitrum` and `Arbitrum Bridge`.

fix: adjust Arbitrum One name

---

README.md
src/chains/SolanaChain.ts
src/chains/chain.utils.ts
src/chains/supported.chains.ts

Added metamask (network) information to Solana chain. Thus the SolanaChain type and EVMChain type should be the same. However, merging them into a common chain object can be breaking and should be done in a separate task.

fix: update solana supported chains to include network information

---

src/api.ts
src/base.ts

We don't want to support this endpoint anymore in the future. /chains, /tools, /connections, and /tokens should be used instead

feat: deprecate the possibilities endpoint

---

package.json

The `install` script was previously used when using uncompiled types locally. The script is not OS independent and not need when loading the package from npm.

fix: remove unused and failing install script

---

src/chains/supported.chains.ts

This is the official RPC mentioned here: https://zkevm.polygon.technology/docs/develop#connecting-to-zkevm
Also it's the only green one on chainlist

fix(chains): update zkEVM rpc

---

src/api.ts

We want to handle NOT_PROCESSABLE_REFUND_NEEDED as a part of PENDING status so those txs will be caught up by the job and updated. Currently, txs with FAILED status are not being updated with the /status call, we just return a response from Mongo.

feat: move NOT_PROCESSABLE_REFUND_NEEDED to PENDING

---

src/chains/supported.chains.ts

The old url points to some weird shit explorer that doesn't work

fix: fix zksync block explorer url

---

src/api.ts

https://lifi.atlassian.net/browse/LF-4841
We need `ChainType` in the /connections /tokens and /chains request. This is so that we can filter out chainTypes we don't want.
This is part 1, part2 will be in lifi-backend.

feat: add chainRequest for the /chains endpoint

---

src/chains/Chain.ts
src/chains/supported.chains.ts

Since there are new projects leveraging the Solana virtual machine (SVM) as the execution environment it makes sense to broaden the scope of chainTypes. Previously we used Solana as the chainType for the chain Solana. However, since we are concerned with the execution environments we should rather have the chain Solana be a subset of the chainType SVM.
Note: this is a breaking change and will have to wait for the corresponding backend fix before being merged.
BREAKING CHANGE: This changes the chainType for the Solana chain.

feat(Chain)!: rename chainType Solana to SVM

---

src/api.ts

There are changes from backend in the request config for the analytics API,
https://github.com/lifinance/lifi-backend/pull/2770
[API Reference](https://apidocs.li.fi/reference/get_analytics-wallets-wallet-address-1)

fix: added wallet analytics request type

---

src/api.ts

The get tokens endpoint accepts an array of strings as the parameter for chains. It is documented  [here](https://apidocs.li.fi/reference/get_tokens-1). 
The issue with the current type is that Ajv JsonSchemaType will only accept numbers in the schema, stating this error:
```
Property 'type' is missing in type '{ oneOf: { type: string; $ref: string; }[]; }' but required in type 
'{ type: "number" | "integer"; }'.
```
Even with our current schema that contains chain keys and chain ids it will fail showing this error when passing a chain key:
```
{
"message": "querystring/chains/0 must be integer: /chains/0: must be integer"
}
```

refactor: get tokens request

---

src/api.ts

This reduces the dependencies on `ethers` as a first step for a viem migration.
This does everything: https://github.com/lifinance/types/pull/183
But we want to do it in steps

feat!: replace ethers transaction request with custom implementation

---

src/tokens/base.ts

https://lifi.atlassian.net/browse/LF-2324
the token doesn't have a logo in debank for most of the chains so we need to add it manually in data-types

chore: add frxETH coinkey

---

package.json
src/api.ts

Types for token price historic (/token/historic) request and response.
For https://github.com/lifinance/lifi-backend/pull/5759

feat: add types for token historic

---

package.json
src/api.ts

Aligns with rest of API and data model, avoids storing prices as floats.

chore: change historic token price to string

---

package.json
src/api.ts
src/step.ts

https://lifi.atlassian.net/browse/LF-9536
Exposing `StepInformation` type so that new `/step` endpoint can be used by other services with the return type available.
Needed as part of the Ledger quote flow

feat: add types for step endpoint

---

package.json
src/step.ts

Make the `Action.slippage` field optional.
This is a major-version upgrade to v17.x.x

feat(Action): make action.slippage optional

---

CHANGELOG.md
package.json
src/tokens/base.ts

I am updating the int tests in BE, and we need USDe as test tokens. Also USDe is now widely used in the ecosystem

feat: add USDe token symbol
